apiVersion: v1
kind: Service
metadata:
  name: generate-order-service
  labels:
    app: generate-order-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: generate-order
  type: NodePort
